### ISSUE TITLE
Sentinels Rewrite Config File

### ISSUE THREAD

**Issue by psycotica0** [DavidWittman/ansible-redis#114] opened 2016-08-04 14:11 UTC
If I run the ansible role and deploy sentinels and a normal redis host, and then later I do it again, it looks like the role rewrites the config file, erasing all of the persistence sentinels have stored there about who the slaves are, and the other sentinels, along with who the current master is.

Is there a way around that, or am I doing something wrong?
Is there a way to edit settings without resetting sentinels back to their initial state?

**Comment by DavidWittman** [comment] 2016-09-30 12:52
@psycotica0 This is a dupe of #22. Which I've been meaning to address for far too long. There are some possibilities proposed for fixing that issue, and I've experimented with using the `blockinfile` module as well to avoid overwriting these changes. If you have any suggestions feel free to drop them in that issue.

**Closed by DavidWittman** 2016-09-30 12:52 UTC
