### ISSUE TITLE
Failing with vagrant 1.4.3 + ansible 1.9 (dev)

### ISSUE THREAD

**Issue by MarcosMenegazzo** [DavidWittman/ansible-redis#50] opened 2015-02-25 17:45 UTC
Hello, i'm trying to use your role script to configure a vagrant virtual machine.

My playbook:
```
---
- hosts: all 
  user: vagrant
  sudo: yes 
  roles:
    - DavidWittman.redis
    - database
```

Running "vagrant up" i get:
```
Bringing machine 'payroll' up with 'virtualbox' provider...
[payroll] Importing base box 'precise32'...
[payroll] Matching MAC address for NAT networking...
[payroll] Setting the name of the VM...
[payroll] Clearing any previously set forwarded ports...
[payroll] Clearing any previously set network interfaces...
[payroll] Preparing network interfaces based on configuration...
[payroll] Forwarding ports...
[payroll] -- 22 => 2222 (adapter 1)
[payroll] Booting VM...
[payroll] Waiting for machine to boot. This may take a few minutes...
[payroll] Machine booted and ready!
[payroll] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
[payroll] Configuring and enabling network interfaces...
[payroll] Mounting shared folders...
[payroll] -- /vagrant
[payroll] Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [payroll]

TASK: [DavidWittman.redis | install dependencies] ***************************** 
changed: [payroll] => (item=gcc,make,libc6-dev)

TASK: [DavidWittman.redis | install dependencies] ***************************** 
skipping: [payroll]

TASK: [DavidWittman.redis | enable overcommit in sysctl] ********************** 
changed: [payroll]

TASK: [DavidWittman.redis | add redis user] *********************************** 
changed: [payroll]

TASK: [DavidWittman.redis | download redis] *********************************** 
changed: [payroll]

TASK: [DavidWittman.redis | upload redis] ************************************* 
skipping: [payroll]

TASK: [DavidWittman.redis | extract redis tarball] **************************** 
changed: [payroll]

TASK: [DavidWittman.redis | compile redis] ************************************ 
changed: [payroll]

TASK: [DavidWittman.redis | create redis install directory] ******************* 
ok: [payroll]

TASK: [DavidWittman.redis | create /etc/redis] ******************************** 
changed: [payroll]

TASK: [DavidWittman.redis | create /var/run/redis] **************************** 
changed: [payroll]

TASK: [DavidWittman.redis | install redis] ************************************ 
changed: [payroll]

TASK: [DavidWittman.redis | list redis binaries] ****************************** 
ok: [payroll]

TASK: [DavidWittman.redis | add redis binaries to alternatives] *************** 
failed: [payroll] => (item=redis-benchmark) => {"failed": true, "item": "redis-benchmark", "parsed": false}
SUDO-SUCCESS-ukekmrntwbssexuzjesgrgrsnvxovkqg
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.08-274944950675321/alternatives", line 1723, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.08-274944950675321/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack

failed: [payroll] => (item=redis-check-aof) => {"failed": true, "item": "redis-check-aof", "parsed": false}
SUDO-SUCCESS-herdhrmjwuehyatkopuplogtywaosaph
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.27-64895011136970/alternatives", line 1723, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.27-64895011136970/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack

failed: [payroll] => (item=redis-check-dump) => {"failed": true, "item": "redis-check-dump", "parsed": false}
SUDO-SUCCESS-fyqfxpjfoeilddbqlthcosdoejjphyhf
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.45-51532570914849/alternatives", line 1723, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.45-51532570914849/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack

failed: [payroll] => (item=redis-cli) => {"failed": true, "item": "redis-cli", "parsed": false}
SUDO-SUCCESS-htrsqivxvwgfilfataujadaqqxdrhieq
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.61-128316913027241/alternatives", line 1723, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.61-128316913027241/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack

failed: [payroll] => (item=redis-server) => {"failed": true, "item": "redis-server", "parsed": false}
SUDO-SUCCESS-uvahlwknzeuzpxrpwchvuooglmchmefi
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.79-139109903766318/alternatives", line 1723, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424885715.79-139109903766318/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/menegazzo/playbook.retry

payroll                    : ok=12   changed=9    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Seems to be an issue with ansible, but i have no idea where to start.

Any tips will be welcome.

**Comment by MarcosMenegazzo** [comment] 2015-02-25 18:02
I've just checked Ansible 1.6.3 and tried again. It works. I think now is necessary to try newer versions and check where it fails.

**Comment by MarcosMenegazzo** [comment] 2015-02-25 19:18
This is happening since Ansible 1.8.0.

**Comment by DavidWittman** [comment] 2015-03-08 19:35
Thanks for reporting this. I was able to reproduce this on the current HEAD of Ansible. It is likely a regression in the `alternatives` module; I'll look into a sound solution there.

@MarcosMenegazzo I'm unable to reproduce the issue on versions of Ansible prior to 1.9.x. Could you give me more details about your build environment? Specifically the target guest distribution. I tested on the past two Ubuntu LTS releases and didn't seem to have any problems.

**Comment by MarcosMenegazzo** [comment] 2015-03-09 21:08
Hello @DavidWittman, 
I'm running ansible over Ubuntu 14.04, and my vagrant VM is Ubuntu Precise 32 (12.04 i think). First i tried your script with Ansible HEAD, i got that error you saw. Then i checked tag 1.6.3 and it worked well. And after that, i tried to checked every newer tag of Ansible until i get the error again, and the error reappeared with Ansible 1.8.0.

**Comment by ilganeli** [comment] 2015-03-13 22:26
Hi @DavidWittman is there a fix for this in the mean-time? This is a blocker for us. Thanks!

**Comment by DavidWittman** [comment] 2015-03-13 23:43
The `alternatives` module seems to be broken in a bad way. See https://github.com/ansible/ansible-modules-extras/issues/12 for more details.

I'm going to be removing the `add redis binaries to alternatives` task until it is stable.

**Comment by DavidWittman** [comment] 2015-03-14 03:49
@MarcosMenegazzo @ilganeli @hq-bot I "fixed" this issue by removing these tasks for now.

I also [opened a pull request](https://github.com/ansible/ansible-modules-extras/pull/313) upstream to fix the root of the problem in the `alternatives` module.

Let me know if you're still having any issues.

**Closed by DavidWittman** 2015-03-14 03:49 UTC
Labels: bug

**Comment by ruebrenda** [comment] 2015-04-23 17:45
I'm also seeing this error with Ansible 1.9.0.1.

**Comment by DavidWittman** [comment] 2015-04-23 23:33
@ruebrenda Are you using the latest version of this role? I removed the tasks which were causing these issues in [this commit](https://github.com/DavidWittman/ansible-redis/commit/4764d33f3d7ee11bd9f18b167ea0fc1fff0ebb02), which was a part of the release for version [1.0.3](https://github.com/DavidWittman/ansible-redis/tree/1.0.3).

**Comment by ruebrenda** [comment] 2015-04-24 00:01
@DavidWittman Somehow I ended up here when I was googling for how to resolve this same error on the Ansible alternatives task. Sorry for the confusion.

**Comment by ruebrenda** [comment] 2015-04-24 00:07
@DavidWittman I think I see now. Looks like your merge PR hasn't made it to the release, yet.
